# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemimgtypes',
            name='imgType',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
