# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemimgs',
            name='url',
            field=models.URLField(default='assets/img/noImage_th.png', max_length=2000),
        ),
    ]
