# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemstore', '0002_auto_20160212_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemimgs',
            name='imgType',
            field=models.CharField(choices=[('A', 'John'), ('B', 'Paul'), ('C', 'George'), ('D', 'Ringo'), ('E', 'Thumb')], default='THUMB', max_length=1),
            preserve_default=False,
        ),
    ]
