# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemstore', '0003_auto_20160217_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulldisplays',
            name='reviews',
        ),
    ]
